export const LOGO_SCREEN = "LOGO_SCREEN";
export const LOG_IN_SCREEN = "LOG_IN_SCREEN";
export const LOG_OUT_SCREEN = "LOG_OUT_SCREEN";
export const SIGN_UP_SCREEN = "SIGN_UP_SCREEN";
export const RESET_PASSWORD_SCREEN = "RESET_PASSWORD_SCREEN";
